<div class="row">
	<div class="col-xs-12 col-sm-4">
<?php
$title = 'Delete';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to <code>delete</code> this account?</p>
<form action="" method="post">
<div>
    <br /><input class="btn btn-primary" type="submit" name="delete" value="Yes" />
    <input class="btn btn-warning"  type="submit" name="delete" value="No" />
    
</div>
</form>
<br />
</div>
</div>