

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

/* Styling Form */
$form->setAttribute('class', 'form-signin');
$form->get('identity')->setAttribute('class','form-control')->setAttribute('required','required')->setAttribute('autofocus','autofocus')->setAttribute('placeholder','Email Address');
$form->get('credential')->setAttribute('class','form-control')->setAttribute('required','required')->setAttribute('placeholder','Password');
$form->get('submit')->setAttribute('class','btn btn-lg btn-primary btn-block');
?>
<div class="row">
	<div class="col-xs-12 col-sm-3 col-sm-offset-5">
    <h1><?php echo $this->translate('Sign In'); ?></h1>
<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>
</div></div>
