<table class="table table-striped table-bordered">
<?php 
if(!count($events)) echo '<tr><td> '.$_GET['date'].' <span class="badge btn-warning">No event on this date</span></td></tr>';
?>

<?php foreach($events as $event) : ?>
<tr>
	<td width="30%">
		<span class="label label-success"><?=$event->getEventTitle()?></span> <br />
		Start <span class="label label-warning"><?=$event->getStartOfEvent()->format('M d, Y h:i A')?></span><br />
        End <span class="label label-warning"><?=$event->getEndOfEvent()->format('M d, Y h:i A')?></span><br />
		@<?=$event->getVenue()?>
	</td>
    <td>
    	<?=$event->getPurpose()?>
    </td>
</tr>
<?php endforeach;?>
</table>