<div class="row">
	<div class="col-xs-12 col-sm-4">
<?php
$title = 'Decline Request';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to <code>decline</code> request for 
    '<?php echo $this->escapeHtml($request->getInventory() ); ?>'?
</p>
<form action="<?=$this->url('request/action', array( 'action' => 'decline', 'id' => $id ))?>" method="post">
<div>
	<textarea placeholder="Why?" name="note" class="form-control"></textarea>
    <br /><input class="btn btn-primary" type="submit" name="close" value="Yes" />
    <input class="btn btn-warning"  type="submit" name="close" value="No" />
    
</div>
</form>
<br />
</div>
</div>