<?php echo $this->doctype(); ?>
<?php
$systemTitle = 'Event Manager';
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($systemTitle)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet($this->basePath() . '/css/smoothness/jquery-ui-1.10.4.custom.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a style="color:#F93" class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate($systemTitle) ?></a>
                </div>
                <div class="collapse navbar-collapse">
                
                    <?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
                    <ul class="nav navbar-nav navbar-right">
      
						<?php if(!$this->zfcUserIdentity()): ?>
                        <li><a href="<?php echo $this->url('zfcuser/login') ?>"><center><?php echo $this->translate('Sign In') ?></center></a></li>
                        <?php else: ?>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->zfcUserDisplayName()?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <!--<li class="disabled"><a href="#">Inbox <span class="badge">42</span></a></li>-->
                         <!-- <li><a href="<?=$this->url('zfcuser')?>">My Account</a></li>-->
                         
                          
                          <li class="divider"></li>
                          <li><a class="home_sign_out" href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a></li>
                        </ul>
                        </li>
                        <?php endif; ?>
                        <?php if(!$this->zfcUserIdentity()): ?>
                        <div class="navbar-form navbar-left">
                            <a class="navbar-link" href="<?php echo $this->url('zfcuser/register') ?>"><button class="form-control home_sign_in"><?php echo $this->translate('Create Account') ?></button></a>
                          </div>                    
                        <?php endif ?>
                        
                        
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
