<script src="/js/jquery.datetimepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.datetimepicker.css"/>

<script type="text/javascript">
$(function(){
	$('#startofevent').datetimepicker({format:'Y-m-d H:i',});
	$('#endofevent').datetimepicker({format:'Y-m-d H:i',});	
});
</script>

<?php

$form = $this->form;

$title = 'Add Report for "'.$event->getEventTitle().'"';
$this->headTitle($title);


$form->prepare();
/* Styling */

$form->get('event')->get('report')->setAttribute('class','form-control');
?>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3 shadow">
    <center><h1><?=$title?></h1></center>
    <?=$this->form()->openTag($form)?>
<br />
    Report Details <?=$this->formRow($form->get('event')->get('report'))?>
    Pictures <?=$this->formRow($form->get('event')->get('image-file'))?>
    <br /><input name="submit" type="submit" class="btn btn-lg btn-primary btn-block" /><br />
    <?=$this->form()->closeTag()?>
    </div>
</div>
