<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <?php if($this->isAllowed('inventory', 'add')) : ?>
    <a href="<?=$this->url('inventory/action', array( 'action' => 'add'))?>">
    <span class="btn btn-success fileinput-button btn-xs">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Add Item</span>
    </span></a>
    <?php endif;?>
    <?php if($this->isAllowed('inventory', 'request')) : ?>
    <a href="<?=$this->url('inventory/action', array( 'action' => 'request'))?>">
    <span class="btn btn-success fileinput-button btn-xs">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Request Item</span>
    </span></a>
    <?php endif; ?>
    
    <table class="table">
  		<tr bgcolor="#444">
        	<td style="color:white;">Name</td>
            <td style="color:white;">Category</td>
            <td style="color:white;">Type</td>
            <td style="color:white;">Stock</td>
            <td style="color:white;">Actions</td>
        </tr>
        <?php foreach($list as $entry) : ?>
        <tr>
        	<td><a href="<?=$this->url('inventory/action',array('action' => 'view', 'id' => $entry->getId() ))?>"><?=$entry->getName()?></a></td>
            <td><?=$entry->getCategory()?></td>
            <td><?=$entry->getType()?></td>
            <td><span class="badge <?=($entry->getStock()<0?'badge-red':'badge-green')?>"><?=$entry->getStock()?></span></td>
            <td><div class="btn-group">
              <button type="button" class="btn btn-xs btn-danger dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-cog"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="<?=$this->url('inventory/action',array('action' => 'edit', 'id' => $entry->getId()))?>">Modify</a></li>
              </ul>
            </div>
            </td>
        </tr>
        <?php endforeach; ?>
	</table>

	</div>
</div>