<div class="row">
	<div class="col-xs-12 col-sm-4">
<?php
$title = 'Update Stock '.$inventory->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
current stock <span class="label label-default"><?=$inventory->getStock()?></span> <br><br>

<?php foreach($error as $k => $v):?>
<span class="label label-danger"><?=$v?></span>
<?php endforeach; ?>
<form action="" method="post">
<div>
	<select name="type" class="form-control">
    	<option value="in">IN</option>
        <option value="out">OUT</option>
    </select>
    <input type="text" placeholder="Amount" name="amount" class="form-control" />
    <textarea placeholder="Description" class="form-control" name="description"></textarea>
    
    <br /><input class="btn btn-primary" type="submit" name="update" value="Update" />
    <input class="btn btn-warning"  type="submit" name="update" value="Cancel" />
    
</div>
</form>
<br />
</div>
</div>